services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun --hot run example/index.ts
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
        - action: sync+restart
          path: ./example
          target: /app/example
    ports:
      - 3000:3000
    depends_on:
      - redis
    env_file:
      - .env
