services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis_data:/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun --hot run example/index.ts
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/src
        - action: rebuild
          path: ./example
          target: /app/example
        - action: sync+restart
          path: ./.env
          target: /app/.env
    ports:
      - 3000:3000
    # depends_on:
    #   - redis
    env_file:
      - .env